package com.example.dacs3.dashboard

import android.widget.Toast
import androidx.compose.animation.core.Animatable
import androidx.compose.animation.core.tween
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.gestures.detectDragGestures
import androidx.compose.foundation.layout.*
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material.icons.filled.Close
import androidx.compose.material.icons.filled.Favorite
import androidx.compose.material.icons.filled.Undo
import androidx.compose.material.icons.outlined.Checkroom
import androidx.compose.ui.hapticfeedback.HapticFeedbackType
import androidx.compose.ui.platform.LocalHapticFeedback
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.shadow
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalConfiguration
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.IntOffset
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import coil.compose.AsyncImage
import com.example.dacs3.connectDB.ClothingItem
import com.example.dacs3.connectDB.DashboardViewModel
import kotlinx.coroutines.launch
import kotlin.math.roundToInt

// Class representing a swipeable outfit combination card
data class SwiperOutfit(
    val id: String,
    val top: ClothingItem,
    val bottom: ClothingItem,
    val shoes: ClothingItem? = null
)

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun OutfitSwiperScreen(
    viewModel: DashboardViewModel,
    onBack: () -> Unit
) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    val haptic = LocalHapticFeedback.current
    
    // Get closet items
    val closetItems by viewModel.clothingItems.collectAsState()
    val cleanItems = closetItems.filter { it.status.uppercase() !in listOf("WORN", "IN_WASH") }

    // State for outfit deck
    val outfitsDeck = remember { mutableStateListOf<SwiperOutfit>() }
    val swipedHistory = remember { mutableStateListOf<SwiperOutfit>() }
    var deckGenerated by remember { mutableStateOf(false) }

    // Generate outfits if closet has items
    LaunchedEffect(cleanItems) {
        if (cleanItems.isNotEmpty() && !deckGenerated) {
            val tops = cleanItems.filter { it.category.lowercase().run { contains("top") || contains("áo") || contains("shirt") } }
            val bottoms = cleanItems.filter { it.category.lowercase().run { contains("bottom") || contains("quần") || contains("pants") } }
            val shoesList = cleanItems.filter { it.category.lowercase().run { contains("shoes") || contains("giày") } }

            if (tops.isNotEmpty() && bottoms.isNotEmpty()) {
                val list = mutableListOf<SwiperOutfit>()
                // Generate up to 10 random combinations
                val topShuffled = tops.shuffled()
                val bottomShuffled = bottoms.shuffled()
                val shoesShuffled = shoesList.shuffled()

                val count = minOf(12, topShuffled.size, bottomShuffled.size)
                for (i in 0 until count) {
                    val shoes = if (shoesShuffled.isNotEmpty()) shoesShuffled[i % shoesShuffled.size] else null
                    list.add(
                        SwiperOutfit(
                            id = java.util.UUID.randomUUID().toString(),
                            top = topShuffled[i],
                            bottom = bottomShuffled[i],
                            shoes = shoes
                        )
                    )
                }
                outfitsDeck.addAll(list)
                deckGenerated = true
            }
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Text(
                        "Outfit Matcher",
                        fontWeight = FontWeight.ExtraBold,
                        color = MaterialTheme.colorScheme.primary
                    )
                },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.Filled.ArrowBack, contentDescription = "Back")
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = MaterialTheme.colorScheme.background)
            )
        },
        containerColor = MaterialTheme.colorScheme.background
    ) { innerPadding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(innerPadding),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.SpaceBetween
        ) {
            Text(
                text = "Swipe right to Like, left to Dislike.\nHelp train your AI Style Assistant!",
                color = MaterialTheme.colorScheme.onSurfaceVariant,
                fontSize = 13.sp,
                fontWeight = FontWeight.Medium,
                textAlign = TextAlign.Center,
                modifier = Modifier.padding(horizontal = 24.dp, vertical = 8.dp)
            )

            // Card stack container
            Box(
                modifier = Modifier
                    .weight(1f)
                    .fillMaxWidth()
                    .padding(horizontal = 32.dp, vertical = 16.dp),
                contentAlignment = Alignment.Center
            ) {
                if (outfitsDeck.isEmpty()) {
                    Column(
                        horizontalAlignment = Alignment.CenterHorizontally,
                        verticalArrangement = Arrangement.Center
                    ) {
                        Box(
                            modifier = Modifier
                                .size(72.dp)
                                .background(MaterialTheme.colorScheme.primary.copy(alpha = 0.1f), CircleShape),
                            contentAlignment = Alignment.Center
                        ) {
                            Icon(
                                Icons.Filled.AutoAwesome,
                                null,
                                tint = MaterialTheme.colorScheme.primary,
                                modifier = Modifier.size(36.dp)
                            )
                        }
                        Spacer(modifier = Modifier.height(16.dp))
                        Text(
                            text = "You're all caught up!",
                            fontWeight = FontWeight.Bold,
                            fontSize = 18.sp,
                            color = MaterialTheme.colorScheme.primary
                        )
                        Spacer(modifier = Modifier.height(4.dp))
                        Text(
                            text = "Add more items or try again later.",
                            fontSize = 13.sp,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                        Spacer(modifier = Modifier.height(16.dp))
                        Button(
                            onClick = {
                                deckGenerated = false
                                deckGenerated = true // Triggers regeneration
                            }
                        ) {
                            Text("Refresh Deck")
                        }
                    }
                } else {
                    // Render outfits deck (last item in list is the top card)
                    outfitsDeck.asReversed().forEachIndexed { index, outfit ->
                        // Only let the top card be interactive
                        val isTopCard = outfit == outfitsDeck.first()
                        SwipeableOutfitCard(
                            outfit = outfit,
                            isInteractive = isTopCard,
                            onSwipedLeft = {
                                scope.launch {
                                    // Save negative feedback for items
                                    viewModel.saveClothingFeedback(outfit.top.id ?: "", -1)
                                    viewModel.saveClothingFeedback(outfit.bottom.id ?: "", -1)
                                    outfit.shoes?.id?.let { viewModel.saveClothingFeedback(it, -1) }
                                    
                                    haptic.performHapticFeedback(HapticFeedbackType.LongPress)
                                    swipedHistory.add(outfit)
                                    outfitsDeck.remove(outfit)
                                    Toast.makeText(context, "Disliked outfit 👎", Toast.LENGTH_SHORT).show()
                                }
                            },
                            onSwipedRight = {
                                scope.launch {
                                    // Save positive feedback for items
                                    viewModel.saveClothingFeedback(outfit.top.id ?: "", 1)
                                    viewModel.saveClothingFeedback(outfit.bottom.id ?: "", 1)
                                    outfit.shoes?.id?.let { viewModel.saveClothingFeedback(it, 1) }

                                    haptic.performHapticFeedback(HapticFeedbackType.LongPress)
                                    swipedHistory.add(outfit)
                                    outfitsDeck.remove(outfit)
                                    Toast.makeText(context, "Liked outfit! ❤️", Toast.LENGTH_SHORT).show()
                                }
                            }
                        )
                    }
                }
            }

            // Bottom Buttons for tapping instead of swiping
            if (outfitsDeck.isNotEmpty() || swipedHistory.isNotEmpty()) {
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(bottom = 32.dp, start = 40.dp, end = 40.dp),
                    horizontalArrangement = Arrangement.SpaceEvenly,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    // DISLIKE BUTTON
                    IconButton(
                        onClick = {
                            if (outfitsDeck.isNotEmpty()) {
                                val currentOutfit = outfitsDeck.first()
                                scope.launch {
                                    viewModel.saveClothingFeedback(currentOutfit.top.id ?: "", -1)
                                    viewModel.saveClothingFeedback(currentOutfit.bottom.id ?: "", -1)
                                    currentOutfit.shoes?.id?.let { viewModel.saveClothingFeedback(it, -1) }
                                    
                                    haptic.performHapticFeedback(HapticFeedbackType.LongPress)
                                    swipedHistory.add(currentOutfit)
                                    outfitsDeck.remove(currentOutfit)
                                    Toast.makeText(context, "Disliked outfit 👎", Toast.LENGTH_SHORT).show()
                                }
                            }
                        },
                        enabled = outfitsDeck.isNotEmpty(),
                        modifier = Modifier
                            .size(56.dp)
                            .shadow(if (outfitsDeck.isNotEmpty()) 8.dp else 0.dp, CircleShape, spotColor = MaterialTheme.colorScheme.error.copy(alpha = 0.3f))
                            .background(
                                color = if (outfitsDeck.isNotEmpty()) MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.35f) else MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.15f),
                                shape = CircleShape
                            )
                            .border(1.dp, if (outfitsDeck.isNotEmpty()) MaterialTheme.colorScheme.error.copy(alpha = 0.4f) else MaterialTheme.colorScheme.error.copy(alpha = 0.15f), CircleShape)
                    ) {
                        Icon(
                            Icons.Filled.Close,
                            contentDescription = "Dislike",
                            tint = if (outfitsDeck.isNotEmpty()) MaterialTheme.colorScheme.error else MaterialTheme.colorScheme.error.copy(alpha = 0.4f),
                            modifier = Modifier.size(24.dp)
                        )
                    }

                    // UNDO BUTTON
                    IconButton(
                        onClick = {
                            if (swipedHistory.isNotEmpty()) {
                                val lastOutfit = swipedHistory.removeAt(swipedHistory.size - 1)
                                scope.launch {
                                    viewModel.saveClothingFeedback(lastOutfit.top.id ?: "", 0)
                                    viewModel.saveClothingFeedback(lastOutfit.bottom.id ?: "", 0)
                                    lastOutfit.shoes?.id?.let { viewModel.saveClothingFeedback(it, 0) }
                                    
                                    haptic.performHapticFeedback(HapticFeedbackType.LongPress)
                                    outfitsDeck.add(0, lastOutfit)
                                    Toast.makeText(context, "Undone last swipe", Toast.LENGTH_SHORT).show()
                                }
                            }
                        },
                        enabled = swipedHistory.isNotEmpty(),
                        modifier = Modifier
                            .size(48.dp)
                            .shadow(if (swipedHistory.isNotEmpty()) 6.dp else 0.dp, CircleShape)
                            .background(
                                color = if (swipedHistory.isNotEmpty()) MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.35f) else MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.15f),
                                shape = CircleShape
                            )
                            .border(1.dp, if (swipedHistory.isNotEmpty()) MaterialTheme.colorScheme.primary.copy(alpha = 0.4f) else MaterialTheme.colorScheme.primary.copy(alpha = 0.15f), CircleShape)
                    ) {
                        Icon(
                            imageVector = Icons.Filled.Undo,
                            contentDescription = "Undo",
                            tint = if (swipedHistory.isNotEmpty()) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.primary.copy(alpha = 0.4f),
                            modifier = Modifier.size(20.dp)
                        )
                    }

                    // LIKE BUTTON
                    IconButton(
                        onClick = {
                            if (outfitsDeck.isNotEmpty()) {
                                val currentOutfit = outfitsDeck.first()
                                scope.launch {
                                    viewModel.saveClothingFeedback(currentOutfit.top.id ?: "", 1)
                                    viewModel.saveClothingFeedback(currentOutfit.bottom.id ?: "", 1)
                                    currentOutfit.shoes?.id?.let { viewModel.saveClothingFeedback(it, 1) }
                                    
                                    haptic.performHapticFeedback(HapticFeedbackType.LongPress)
                                    swipedHistory.add(currentOutfit)
                                    outfitsDeck.remove(currentOutfit)
                                    Toast.makeText(context, "Liked outfit! ❤️", Toast.LENGTH_SHORT).show()
                                }
                            }
                        },
                        enabled = outfitsDeck.isNotEmpty(),
                        modifier = Modifier
                            .size(56.dp)
                            .shadow(if (outfitsDeck.isNotEmpty()) 12.dp else 0.dp, CircleShape, spotColor = MaterialTheme.colorScheme.primary.copy(alpha = 0.4f))
                            .background(
                                brush = Brush.linearGradient(
                                    colors = listOf(
                                        MaterialTheme.colorScheme.primary,
                                        MaterialTheme.colorScheme.secondary
                                    )
                                ),
                                shape = CircleShape,
                                alpha = if (outfitsDeck.isNotEmpty()) 1.0f else 0.4f
                            )
                    ) {
                        Icon(
                            Icons.Filled.Favorite,
                            contentDescription = "Like",
                            tint = MaterialTheme.colorScheme.onPrimary,
                            modifier = Modifier.size(24.dp)
                        )
                    }
                }
            }
        }
    }
}

@Composable
fun SwipeableOutfitCard(
    outfit: SwiperOutfit,
    isInteractive: Boolean,
    onSwipedLeft: () -> Unit,
    onSwipedRight: () -> Unit
) {
    val density = androidx.compose.ui.platform.LocalDensity.current
    val screenWidth = LocalConfiguration.current.screenWidthDp.dp
    val screenWidthPx = with(density) { screenWidth.toPx() }
    val swipeThreshold = screenWidthPx * 0.4f // Threshold in pixels (40% of screen width)

    val offsetX = remember { Animatable(0f) }
    val offsetY = remember { Animatable(0f) }
    val scope = rememberCoroutineScope()

    Card(
        modifier = Modifier
            .fillMaxWidth()
            .height(440.dp)
            .shadow(
                elevation = if (isInteractive) 16.dp else 4.dp,
                shape = RoundedCornerShape(28.dp)
            )
            .graphicsLayer {
                translationX = offsetX.value
                translationY = offsetY.value
                rotationZ = offsetX.value / 15f // Rotate as it slides
            }
            .pointerInput(isInteractive) {
                if (!isInteractive) return@pointerInput
                detectDragGestures(
                    onDragEnd = {
                        if (offsetX.value > swipeThreshold) {
                            // Fly right
                            scope.launch {
                                offsetX.animateTo(swipeThreshold * 2, tween(200))
                                onSwipedRight()
                            }
                        } else if (offsetX.value < -swipeThreshold) {
                            // Fly left
                            scope.launch {
                                offsetX.animateTo(-swipeThreshold * 2, tween(200))
                                onSwipedLeft()
                            }
                        } else {
                            // Snap back
                            scope.launch {
                                offsetX.animateTo(0f, tween(150))
                                offsetY.animateTo(0f, tween(150))
                            }
                        }
                    },
                    onDrag = { change, dragAmount ->
                        change.consume()
                        scope.launch {
                            offsetX.snapTo(offsetX.value + dragAmount.x)
                            offsetY.snapTo(offsetY.value + dragAmount.y)
                        }
                    }
                )
            },
        shape = RoundedCornerShape(28.dp),
        border = BorderStroke(1.dp, MaterialTheme.colorScheme.onSurface.copy(alpha = 0.08f)),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.35f))
    ) {
        Box(modifier = Modifier.fillMaxSize()) {
            Column(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(20.dp),
                horizontalAlignment = Alignment.CenterHorizontally,
                verticalArrangement = Arrangement.SpaceAround
            ) {
                // Top Clothing Item
                SwipeCardItemRow("Top", outfit.top)

                HorizontalDivider(color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.05f))

                // Bottom Clothing Item
                SwipeCardItemRow("Bottom", outfit.bottom)

                if (outfit.shoes != null) {
                    HorizontalDivider(color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.05f))
                    // Shoes Clothing Item
                    SwipeCardItemRow("Shoes", outfit.shoes)
                }
            }

            // Overlay Stamps
            val dragRatio = (offsetX.value / swipeThreshold).coerceIn(-1.5f, 1.5f)
            if (dragRatio > 0.1f) {
                Box(
                    modifier = Modifier
                        .align(Alignment.TopStart)
                        .padding(24.dp)
                        .graphicsLayer { rotationZ = -15f }
                        .border(3.dp, Color(0xFF4CAF50).copy(alpha = dragRatio.coerceIn(0f, 1f)), RoundedCornerShape(8.dp))
                        .padding(horizontal = 12.dp, vertical = 6.dp)
                ) {
                    Text(
                        text = "LIKE",
                        color = Color(0xFF4CAF50).copy(alpha = dragRatio.coerceIn(0f, 1f)),
                        fontWeight = FontWeight.ExtraBold,
                        fontSize = 22.sp
                    )
                }
            } else if (dragRatio < -0.1f) {
                Box(
                    modifier = Modifier
                        .align(Alignment.TopEnd)
                        .padding(24.dp)
                        .graphicsLayer { rotationZ = 15f }
                        .border(3.dp, Color(0xFFE57373).copy(alpha = (-dragRatio).coerceIn(0f, 1f)), RoundedCornerShape(8.dp))
                        .padding(horizontal = 12.dp, vertical = 6.dp)
                ) {
                    Text(
                        text = "PASS",
                        color = Color(0xFFE57373).copy(alpha = (-dragRatio).coerceIn(0f, 1f)),
                        fontWeight = FontWeight.ExtraBold,
                        fontSize = 22.sp
                    )
                }
            }
        }
    }
}

@Composable
fun SwipeCardItemRow(label: String, item: ClothingItem) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = 4.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Card(
            modifier = Modifier.size(90.dp),
            shape = RoundedCornerShape(16.dp),
            border = BorderStroke(1.dp, MaterialTheme.colorScheme.onSurface.copy(alpha = 0.05f))
        ) {
            if (item.imageUrl.isNotEmpty()) {
                AsyncImage(
                    model = item.imageUrl,
                    contentDescription = item.clothes_name,
                    contentScale = ContentScale.Crop,
                    modifier = Modifier.fillMaxSize()
                )
            } else {
                Box(
                    modifier = Modifier
                        .fillMaxSize()
                        .background(MaterialTheme.colorScheme.surfaceVariant),
                    contentAlignment = Alignment.Center
                ) {
                    Icon(Icons.Outlined.Checkroom, null, modifier = Modifier.size(36.dp))
                }
            }
        }

        Spacer(modifier = Modifier.width(16.dp))

        Column(modifier = Modifier.weight(1f)) {
            Text(
                text = label.uppercase(),
                fontSize = 10.sp,
                fontWeight = FontWeight.ExtraBold,
                color = MaterialTheme.colorScheme.secondary,
                letterSpacing = 1.sp
            )
            Spacer(modifier = Modifier.height(2.dp))
            Text(
                text = item.clothes_name,
                fontSize = 16.sp,
                fontWeight = FontWeight.Bold,
                color = MaterialTheme.colorScheme.primary,
                maxLines = 1,
                overflow = TextOverflow.Ellipsis
            )
            Text(
                text = "Color: ${item.mainColor ?: "N/A"}",
                fontSize = 12.sp,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
        }
    }
}
